# Runtime configuration for hosting cap_collector on Google AppEngine.
# See https://cloud.google.com/appengine/docs/python/config/appconfig

application: cap-tools
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: MySQLdb
  version: "latest"

- name: lxml
  version: "latest"

- name: ssl
  version: latest

handlers:
- url: /client
  static_dir: client
  secure: always

- url: .*
  script: CAPCollector.wsgi.application
  secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: 'CAPCollector.settings'

